I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 38, in script
    Jessica "This is the store"
Exception: Sayer 'Jessica' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 38, in script
    Jessica "This is the store"
  File "/Users/jessicawilkins/Desktop/renpy-7.4.10-sdk/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/jessicawilkins/Desktop/renpy-7.4.10-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Jessica' is not defined.

Darwin-20.6.0-x86_64-i386-64bit
Ren'Py 7.4.10.2178
Day in the life Game 1.0
Fri Dec  3 01:00:10 2021
